Feature/ds 7801 websocket1
agevorgy/texas-holdem-2.0 pull request #5
Opened 2018-07-06 14:02 UTC by agevorgy

2018-07-06 14:07 UTC, cpm5041 approved these changes

2018-07-06 14:26 UTC, juanflo requested changes

2018-07-06 14:26 UTC, juanflo commented on app.js
> +    console.log(data);
Shouldn't we broadcast to all clients?

2018-07-06 14:26 UTC, juanflo commented on app.js
> +var http = require('http');
`express().listen()` returns an http server so you don't need to import it.

2018-07-06 14:47 UTC, agevorgy commented on app.js
> +    console.log(data);
yes, but this is just the basic connection. we're working on broadcasting to all the clients now

2018-07-12 15:10 UTC, juanflo requested changes

2018-07-12 15:10 UTC, juanflo commented on package.json
> +    "shortid": "^2.2.8",
I'm assuming you are using this one. Can you remove `short-id` above it. `yarn remove short-id`.

2018-07-12 15:16 UTC, juanflo approved these changes

2018-07-12 15:17 UTC, merged