configure join session web sockets
agevorgy/texas-holdem-2.0 pull request #6
Opened 2018-07-16 19:51 UTC by vickyteng

2018-07-16 20:16 UTC, aigyptios requested changes

2018-07-16 20:16 UTC, aigyptios commented on app.js
> +    // Session.findOne( { id: data.sessionId }, (err, sessions) => {
Remove commented-out code.

2018-07-17 16:52 UTC, juanflo approved these changes

2018-07-17 18:27 UTC, aigyptios approved these changes

2018-07-17 18:29 UTC, merged